name: aep_hourly

dependencies:
  - python
  - pip
  - jupyter
  
  - pandas
  - numpy
  
  - matplotlib
  - seaborn
  - plotly
  
  - scipy
  - statsmodels
  
  - scikit-learn
  - xgboost
  - tensorflow